
Running tests...
----------------------------------------------------------------------
E
======================================================================
ERROR [0.001s]: reader_factory_tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/usr/lib/python3.10/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: reader_factory_tests
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/awais/PycharmProjects/DataFeedTask/src/unittest/python/reader_factory_tests.py", line 3, in <module>
    from src.main.python.reader_factory import ReaderFactory
ModuleNotFoundError: No module named 'src'


----------------------------------------------------------------------
Ran 1 test in 0.008s

FAILED (errors=1)

Generating XML reports...
